# Generated by Django 3.0 on 2019-12-30 20:50

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название категории')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('page_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы')),
                ('page_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание категории')),
                ('old_id', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('isMain', models.BooleanField(default=True, verbose_name='Основная категория?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Category', verbose_name='Относмтся к категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image', verbose_name='Основное изображение ')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название ')),
                ('name_lower', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price', models.IntegerField(db_index=True, default=0, verbose_name='Цена')),
                ('discount', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Скидка %')),
                ('page_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1')),
                ('page_title', models.CharField(max_length=255, null=True, verbose_name='Название страницы')),
                ('page_description', models.TextField(null=True, verbose_name='Описание страницы')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('description_main', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание краткое')),
                ('description_demo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание для демо')),
                ('chertezh_list', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Информация о проекте')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('model', models.CharField(default='не указано', max_length=15, verbose_name='Model')),
                ('sku', models.CharField(default='не указано', max_length=15, verbose_name='SKU')),
                ('file', models.CharField(default='не указано', max_length=15, verbose_name='Файл')),
                ('old_id', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Отображать товар ?')),
                ('buys', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Промокод (для создания рандомного значения оставить пустым)')),
                ('promo_discount', models.IntegerField(default=0, verbose_name='Скидка на заказ')),
                ('use_counts', models.IntegerField(blank=True, default=1, verbose_name='Кол-во использований')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Неограниченное кол-во использований')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('expiry', models.DateTimeField(default=datetime.datetime(2019, 12, 30, 20, 50, 20, 77297), verbose_name='Срок действия безлимитного кода')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название подкатегории')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('page_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы')),
                ('page_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание подкатегории')),
                ('views', models.IntegerField(default=0)),
                ('old_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image', verbose_name='Изображение')),
                ('image_descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('old_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение для товара',
                'verbose_name_plural': 'Изображения для товара',
            },
        ),
    ]
