# Generated by Django 3.0 on 2019-12-30 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 22, 29, 54, 210571), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
