# Generated by Django 3.0 on 2019-12-31 00:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20191230_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Отображать категорию?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Category', verbose_name='Относится к категории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название '),
        ),
        migrations.AlterField(
            model_name='item',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание страницы'),
        ),
        migrations.AlterField(
            model_name='item',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 0, 5, 28, 241133), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
