# Generated by Django 3.0 on 2020-03-11 19:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20191231_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcats', to='item.Category', verbose_name='Относится к категории'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 19, 55, 41, 99704), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
