# Generated by Django 3.0 on 2020-03-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20200311_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия безлимитного кода'),
        ),
    ]
