# Generated by Django 3.0 on 2020-06-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20200311_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order_num',
            field=models.IntegerField(default=0),
        ),
    ]
